name: Manually trigger an Azure Machine Learning job
on:
  workflow_dispatch:
    inputs:
      training_data:
        required: true
        type: string
      reg_rate:
        required: true
        type: number
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: bash
      continue-on-error: true
    - name: run job
#       run: bash ${GITHUB_WORKSPACE}/bash/run-job.sh job.yml
#       working-directory: src
      run: |
       az ml job create --file job.yml --training_data ${{ inputs.training_data }} --reg_rate ${{ inputs.reg_rate }} 
      working-directory: src
    
    



