name: Manually trigger an Azure Machine Learning job
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches:
      - main
      - sdk-preview
    paths:
      - src/job.yml
      - bash/run-job.sh
      - bash/setup.sh

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: bash
      continue-on-error: true
    - name: run job
      run: bash -x ../../../bash/run-job.sh job.yml
      working-directory: src
    
    



